### ISSUE TITLE
Non-urgent issue: How to check if Mac is using the correct quicklook plugin?

### ISSUE THREAD

**Issue by Ken0sis** [sbarex/QLMarkdown#100]
I have multiple quicklook plugins that sometimes overlap and conflict with QLMarkdown.  Is there a way to check which quicklook plugin is used for a given file?  I thought there was a way to do it using the command `qlmanage`, but it doesn't seem to be the case anymore.

Thanks

**Comment by sbarex** [comment]
On the system settings, extensions, quicklook, try to drag the qlmarkdown in top of the list

**Comment by Ken0sis** [comment]
Thanks, I understand that I can force the priority of my quicklook plugins (and you've kindly showed me how to do that before), but I want to know if there's a way to check which quicklook plugin is currently used for a given file.  This is to help me debug when a quicklook plugin is not being activated properly.

**Comment by hazarek** [comment]
> Thanks, I understand that I can force the priority of my quicklook plugins (and you've kindly showed me how to do that before), but I want to know if there's a way to check which quicklook plugin is currently used for a given file. This is to help me debug when a quicklook plugin is not being activated properly.

you can enable debug mode

Debug info | Insert in the output some debug information.
-- | --

**Comment by Ken0sis** [comment]
Thanks, but how do I enable debug mode?  Debug mode of qlmange or of QLMarkdown?

**Comment by sbarex** [comment]
In the QLMarkdown advanced settings there is the debug option that add on every rendered file a header with the current settings.

**Comment by Ken0sis** [comment]
Wow, ok ... I had no idea about pluginkit.  Thanks for clarifying what's the debug option in QLMarkdown, and also referring me to pluginkit.  

This kind of knowledge about how to resolve quicklook conflict and how to troubleshoot quicklook extensions/plugins should be published somewhere.  I'm semi-tech-savvy and I couldn't find the answer by googling.
