### ISSUE TITLE
Option to disable page border

### ISSUE THREAD

**Issue by ottob** [sbarex/QLMarkdown#113]
Thanks for a very useful plugin. I only have a small suggestion: right now there is a frame/border around the content:

<img width="1151" alt="Screenshot 2022-08-31 at 19 53 34" src="https://user-images.githubusercontent.com/67104/187746618-a5e5ea3b-f9ed-496e-b3b9-c68d2ad58369.png">

I think it looks a bit weird how the top border disappears into the top of the window, you can only see the top border if you try to scroll down.

Could you add an advanced option to disable the border? Or perhaps add some margin to the top so the top border becomes visible by default?

**Comment by hazarek** [comment]
Hello, I wrote this css property. You can set this by changing the CSS file.

Here is the relevant line;

https://github.com/sbarex/QLMarkdown/blob/b94a02dd2ef50c9080a965b93cd37a53e313daf3/Resources/default.css#L150

**Comment by hazarek** [comment]
to remove the Border

Change this line
https://github.com/sbarex/QLMarkdown/blob/b94a02dd2ef50c9080a965b93cd37a53e313daf3/Resources/default.css#L155

to;
`border-style: None; `

**Comment by ottob** [comment]
Thanks for the help. That worked.
