### ISSUE TITLE
Can not use Quick Look

### ISSUE THREAD

**Issue by zhyiyu** [sbarex/QLMarkdown#115]
Hi, thank you so much for creating the app. I followed the instruction and installed version 10.0.15.

However, I still can not view the `.md` files via Quick Look:
<img width="700" alt="QL" src="https://user-images.githubusercontent.com/26550166/205228646-54173634-05d5-4765-b6db-68798d65b409.png">

What I did:
- I launched the application at least once.
- I moved the application to `Trash` and back in the `Application` folder.
- I ensured that the `QLMarkdown` is on the top of `Quick Look` `Extensions` in the `System Preferences`. (Please see the screenshot below.)
- The output of `mdls -name kMDItemContentType readme.md` for me is `kMDItemContentType = "net.daringfireball.markdown"`.

<img width="780" alt="settings" src="https://user-images.githubusercontent.com/26550166/205229308-491898d5-6986-46c3-ba7b-7484888d66e5.png">

Please let me know if you need more information, thank you in advance for the help!

**Comment by sbarex** [comment]
I don't know, maybe it depends on the program associated with the .md files

**Comment by zhyiyu** [comment]
The Quick Look works today like a miracle, I have no idea why, but it works now.

<img width="918" alt="readme" src="https://user-images.githubusercontent.com/26550166/217402789-0f5010ea-67a8-4509-b25c-24e40d7ac216.png">
