### ISSUE TITLE
Feature Request: Rendering .rst files as well?

### ISSUE THREAD

**Issue by ctismer** [sbarex/QLMarkdown#117]
Hi sbarex,

QLMarkdown is a really nice extension to the finder. I mainly use it to preview .mkv files, but the markdown viewing is very convenient!

Since I am a CPython and PySide/C++ developer, most documentation source is still in Rich Text format (.rst).
It would be great if we could see our ReST files and others directly in the finder as well.

Questions: 
* Do you have plans to support more extension types?
* Is there an API defined for writing such an extension, myself?

Thank you so much for reviving this project!

**Comment by sbarex** [comment]
This application depends too much on the `cmark` rendering engine to support other markup languages.
I had started experimenting with using `PanDoc` for rendering but I didn't have time to continue it.

My other application [SourceCodeSyntaxHighlight](https://github.com/sbarex/SourceCodeSyntaxHighlight), for previewing source files, supports viewing `.rst` files although only source code and not final formatting.

For the development of new QuickLook extensions the starting point is the official documentation: https://developer.apple.com/documentation/quicklook

**Comment by ctismer** [comment]
Thanks a lot!
