### ISSUE TITLE
Background flashes white before turning black (in dark mode)

### ISSUE THREAD

**Issue by nobugshere** [sbarex/QLMarkdown#118]
In version 1.0.16, with the system set to dark mode, when the quick look window is initially displayed it flashes white before turning the background black.  I don't recall the previous version doing that.  It's very annoying when your eyes are adapted to the dark backgrounds.

Environment:
QLMarkdown 1.0.16 (via Homebrew)
Mac Studio M1 Max
MacOS 13.3.1 (a) Ventura

**Comment by sbarex** [comment]
I think this is a common problem on macOS that affects all previews including those generated by the operating system

**Comment by nobugshere** [comment]
I played with it some more and maybe it does happen with the built-in previewers but, most of the time, it must be so quick I don't notice it.  I downgraded to 1.0.15 and it flashes as well but it usually seems shorter than 1.0.16, but not always.  I'll close this issue but, if you can find a way to minimize the flash, it would be appreciated.  In any case, thank you for a good tool that filled the exact niche I needed!
