### ISSUE TITLE
The title of the exported HTML document is always `.md`

### ISSUE THREAD

**Issue by setanarut** [sbarex/QLMarkdown#124]
The title of the exported HTML document (`⌘ E`) is always `.md`. It must be the same as the current file name. There should be a box where you can manually enter a title or extract it from the file name.

```html
<title>.md</title>
```
![Ekran Resmi 2023-11-05 16 17 30](https://github.com/sbarex/QLMarkdown/assets/36481442/c8c7638f-2f11-491e-b174-e40489b1b9b6)

#### for example:

document_about_something.md -> `<title>document_about_something</title>`

#### or formatted version: 

document_about_something.md -> `<title>Document about something</title>`

**Comment by keriheuer** [comment]
Wondering if there's any progress on this? I just downloaded QLMarkdown and this is still happening.

**Comment by setanarut** [comment]
> Wondering if there's any progress on this? I just downloaded QLMarkdown and this is still happening.

The only solution at the moment is to open the HTML file in the editor and change the `<title>.md</title>` line. Sbarex is not around.

**Comment by sbarex** [comment]
Fixed on release 1.0.18.
