### ISSUE TITLE
Although QLMarkdown.app can open the .md file, it does not appear in the "Open With" menu.

### ISSUE THREAD

**Issue by setanarut** [sbarex/QLMarkdown#125]
Although QLMarkdown.app can open the .md file, It does not appear in the "Open With" menu when you right-click. It always needs to be set as default.

**Comment by sbarex** [comment]
QLMarkdown was not developed to be a standalone markdown viewer, but only to provide Quick View functionality. The app must be used only to configure the appearance of the Quick Look preview.

**Comment by setanarut** [comment]
It's true from your point of view, but there's no reason why it shouldn't be standalone. I use Interface because the command line tool doesn't convert properly.

**Comment by Kolsha** [comment]
I would also use it as standalone
