### ISSUE TITLE
Auto-repeat Page Down leads to navigation loss

### ISSUE THREAD

**Issue by martinpk** [sbarex/QLMarkdown#137]
If I hold Page Down (Fn + DownArrow on my Apple BT keyboard) long enough to auto-repeat, then let go of the keys before the end of the document, the contents continue scrolling until it hits the end. I can then no longer navigate up or down the document via keyboard or mouse; I can only close the document.

**Comment by sbarex** [comment]
I'm afraid it's an operating system bug, the app creates a simple html page after which the operating system handles the display and interaction with the user

**Comment by martinpk** [comment]
OK, thanks!
