### ISSUE TITLE
TOC links containing the letter İ do not work.

### ISSUE THREAD

**Issue by setanarut** [sbarex/QLMarkdown#138]
TOC links containing the letter `İ` do not work. Clicking on links containing the Turkish character `İ` does not jump to the relevant title. VSCode `Markdown All in One` Extension and GitHub site do not have this problem.

Click on the `İnsan` or `Deneme İşte İnek` link in the file below. It does not jump.

[test.md](https://github.com/user-attachments/files/16571082/test.md)

**Comment by sbarex** [comment]
The `Deneme İşte İnek` will be converted to the anchor `deneme-işte-inek`. Is the lowercase conversion correct?

**Comment by setanarut** [comment]
The generated line -> `<li><a href="#i%CC%87nsan">İnsan</a></li>`

The generated line is the same but the link generated by QLMarkdown is not working. I don't understand why.

Also The letter that appears in the browser's address bar is a letter with double dot (`qlmarkdown.html#i̇nsan`). In Turkish it should be `i`, but I guess that's not important. VScode extension and GitHub site are also like this.

![Ekran Resmi 2024-08-11 17 26 37](https://github.com/user-attachments/assets/97dcfcac-ecb1-499b-9ca7-d2e08decc3a5)

`vscode.html` that I saved with vscode works, `qlmarkdown.html` does not work. -> [vscode-qlmarkdown.zip](https://github.com/user-attachments/files/16574010/vscode-qlmarkdown.zip)

**Comment by setanarut** [comment]
Yes. Here are the HTML files I saved with VScode and QLMarkdown. The QLMarkdown one doesn't work.-> [qlmarkdown-vscode.zip](https://github.com/user-attachments/files/16574078/qlmarkdown-vscode.zip)

My settings. `Heads anchor` is selected.

![Ekran Resmi 2024-08-11 17 50 49](https://github.com/user-attachments/assets/c638b393-23c1-44bb-8a1e-45f393b19e72)


my settings

**Comment by sbarex** [comment]
In the application settings you have enabled the extension `heads anchor`?

<img width="1050" alt="Screenshot 2024-08-11 alle 16 45 41" src="https://github.com/user-attachments/assets/eaff4706-82ae-4442-b4bb-7eef348ca135">

The extension insert an anchor for every heads on the md file. The anchor is created from the title, set to lowercase, with non-letter symbols removed, and spaces replaced with dashes.

The question is how the letter `İ` should be converted into lowercase. My code translate it to a normal `i` accord to [unicode rule](https://www.compart.com/en/unicode/U+0130). But some other software adopt the `i̇`.

**Comment by setanarut** [comment]
selected yes. I just sent an incorrect reply and deleted it.

**Comment by sbarex** [comment]
The problem is that in your toc you have the link to `#i̇nsan` (with double dot over the i), but the generated anchor title is `#insan` (with a plain latin i)

**Comment by setanarut** [comment]
> The problem is that in your toc you have the link to `#i̇nsan` (with double dot over the i), but the generated anchor title is `#insan` (with a plain latin i)

I can't see any difference between the two. Why is `vscode.html` working properly?

![Ekran Resmi 2024-08-11 18 27 11](https://github.com/user-attachments/assets/1d6ac1f4-13e1-475e-81d9-5803857021d3)

**Comment by sbarex** [comment]
In your vcode.html the head id is `i̇nsan` (note the `i` with the double dot) so the anchor in the TOC works.
In your screenshot is not visible the double dot (font problem? or you font missing some unicode glyphs?)

<img width="586" alt="Screenshot 2024-08-11 alle 19 38 58" src="https://github.com/user-attachments/assets/3425ee07-a441-4c22-8de3-17adaf66f2ce">

**Comment by setanarut** [comment]
> In your vcode.html the head id is `i̇nsan` (note the `i` with the double dot) so the anchor in the TOC works. In your screenshot is not visible the double dot (font problem? or you font missing some unicode glyphs?)

Ahh thanks. I was able to see it when I changed the font to `Menlo`. Then this is a bug related to QLMarkdown.

**Comment by sbarex** [comment]
I'm not sure if it's a qlmarkdown bug. As said before the lover case of `İ` is a plain latin `i` (see unicode and wiki rules). Also I use the standard cpp to translate a widestring to lowercase.

**Comment by setanarut** [comment]
Yes but this is not `i` character -> `<li><a href="#i%CC%87nsan">İnsan</a></li>`

it should convert it like this. it doesn't work because there are two different letters.
`<li><a href="#insan">İnsan</a></li>`

**Comment by setanarut** [comment]
Encodings for URL. QLMarkdown is not matching properly.

| `İ` | `%C4%B0`  |
|---|---------|
| `i̇` | `i%CC%87` |
