### ISSUE TITLE
Feature Request: Export to PDF

### ISSUE THREAD

**Issue by lucasstinis** [sbarex/QLMarkdown#139]
**Feature description**: I'm sorely missing a way to export the preview content (i.e. rendered MD) to PDF.

I don't mean as in printing the document (although that would be a nice feature to add after), but just saving it to a continuous PDF (i.e. without pages).

**Use case**: Storage / archiving of information. This is something I end up doing quite a bit for work and hobby purposes.

Is that viable / something you are thinking of including some day?

P.S. Thanks for sharing this great piece of software!

**Comment by sbarex** [comment]
I'm sorry but this is a feature that can't be implemented. The application is born to provide quick look preview functionality. Furthermore, the rendering engine adopted (the fork developed by GitHub) does not provide output to PDF.
