### ISSUE TITLE
Feature Request: Support Shortcut App 

### ISSUE THREAD

**Issue by liwenkun** [sbarex/QLMarkdown#146]
Hope to provide shortcut for the Shortcut App

**Comment by sbarex** [comment]
You can call the cli utility with a shell script from the Shortcut.

**Comment by liwenkun** [comment]
> You can call the cli utility with a shell script from the Shortcut.

Finally, I use `qlmanage -p /path/to/my.markdown`  to achieve my purpose. Thanks for your reply.

**Comment by sbarex** [comment]
Implemented on release 1.0.21.
