### ISSUE TITLE
Saved changes are applied with a delay.

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#15]
The changes are reflected even without a Finder restart but it takes more time. It was nearly one minute on my machine at one point. But like @sbarex said some caching issues. Maybe there is a way to tell macOS to force prune the cache?

_Originally posted by @relikd in https://github.com/sbarex/QLMarkdown/issues/3#issuecomment-751480287_

**Comment by sbarex** [comment]
The host application and the extension share preferences, however the extension loads them at startup and no longer updates them until your process is terminated. So if you keep the ql markdown preview open or if you continue to view other .md files in quick succession the extension is not released and therefore the preferences are not updated.

I don't know if it is appropriate to force the loading of preferences every time a file is read (with a performance penalty) or to keep things like this.

**Comment by hazarek** [comment]
this is not an important issue,  Live update is required while creating theme (while writing css). The changes I made in "custom.css" appear instantly with the refresh button.

**Comment by sbarex** [comment]
Yes, because the css file is reload every time.

**Comment by relikd** [comment]
> I don't know if it is appropriate to force the loading of preferences every time a file is read

You could also place an empty file in the shared group directory. And only check whether the file exists on every parse. If the file exists, reload the preferences and delete the temporary file.
(Unless there is a way to directly communicate with the extension. Idk. e.g. the network extension has an API to send data from the host app to the extension. Maybe there is a similar method for QL extensions?)

**Comment by sbarex** [comment]
In next release I use a message notification to force the settings refresh.

**Comment by sbarex** [comment]
Fixed in 1.0b7.
