### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#21]
<img width="419" alt="Ekran Resmi 2020-12-29 21 50 00" src="https://user-images.githubusercontent.com/36481442/103307003-08ae9480-4a20-11eb-979d-db9c64ea9f0a.png">

I think it happened because the application name changed.

**Comment by chrismessina** [comment]
Getting this error too. Deleted the app and installed from the new release.

**Comment by sbarex** [comment]
Yes, it is possibile.
I have upload another binary with a fix for the release number.
