### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#24]
1. Factory reset option for reset all settings.
2. Line numbers should be turned off by default. does not fit the default theme. ( Github style )
3. The editor on the left should use a `monospace` font by default. (Menlo)

**Comment by sbarex** [comment]
Implemented on release 1.0b10.

**Comment by hazarek** [comment]
@sbarex 
Version 1.0 (11) this is still the same.

- Line numbers should be turned off by default. does not fit the default theme. ( Github style )
