### ISSUE TITLE
Lag while page scrolling and header anchor jumping

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#27]
Only when viewing in full screen. I am experiencing heavy freezes when scrolling two fingers. this only happens in .md preview with qlmarkdown.

1. View a long markdown file in full screen and swipe with your finger.
2. Click on the table of contents, it jumps with a few seconds delay.

For this reason I could not test other settings. https://github.com/sbarex/QLMarkdown/issues/25. Also "`open on default browser`" doesn't work.

**Comment by sbarex** [comment]
This is another Apple Bug... Webkit inside a quicklook preview is very buggy... so I can't fix it and when i tried to send feedback to apple it never replied.

Opening in browser doesn't work on big sur due to some obscure security problem ... does anyone know how to get around it?

**Comment by hazarek** [comment]
> Webkit inside a quicklook preview is very buggy

This does not happen with html files, only when the Qlmarkdown Quicklook window is displayed.

**Comment by sbarex** [comment]
Sure, it's a bug only for extensions developed by third parties.
The system for the most part still uses the old qlgenerator api(!) and displays the contents inside html views.

On big sur it would not even be possible to use webkit inside the quicklook preview due to a bug in the security entitlements management ...

In fact, if I use the deprecated and obsolete WebView api this problem is not there (and not even that related to safety)!

**Comment by sbarex** [comment]
It should be understood if it is convenient to use the deprecated API only for bigsur thus circumventing the problem or if to leave it as is.

**Comment by hazarek** [comment]
leave it as

**Comment by sbarex** [comment]
`open on default browser` should be fixed with release 1.0b11 on big sur.

For the delay of internal link... I don't understand what this is due to ... even in this case it shouldn't depend on my code.

**Comment by hazarek** [comment]
> `open on default browser` should be fixed with release 1.0b11 on big sur.
> 
> For the delay of internal link... I don't understand what this is due to ... even in this case it shouldn't depend on my code.

I got it, maybe it will be solved in the future. Thank you

**Comment by hazarek** [comment]
@sbarex  your release is not an app bundle.
<img width="152" alt="Ekran Resmi 2020-12-30 21 34 42" src="https://user-images.githubusercontent.com/36481442/103373757-d7e56280-4ae6-11eb-8a8f-0bf60fa07c96.png">

**Comment by sbarex** [comment]
Fixes, the application zip did not load.

**Comment by hazarek** [comment]
ok, I updated it from the menu. it gave an error at first.
