### ISSUE TITLE
save button doesn't work

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#3]
<img width="402" alt="Ekran Resmi 2020-12-27 00 49 31" src="https://user-images.githubusercontent.com/36481442/103159689-7a4ad080-47dd-11eb-912c-6b3bafcb10a1.png">
<img width="211" alt="Ekran Resmi 2020-12-27 00 49 02" src="https://user-images.githubusercontent.com/36481442/103159693-7d45c100-47dd-11eb-9fed-e9bbd5e0e7ac.png">

**Comment by sbarex** [comment]
The extension `inline local images` is on?

**Comment by hazarek** [comment]
Yes, I found the problem. When I relaunch finder, the permission dialog appeared and was fixed. the save button does not work. After restarting finder, the settings are applied.

**Comment by sbarex** [comment]
MacOS handle the preferences with a cache system. 
Perhaps by restarting the Finder they had not had time to save themselves?

**Comment by hazarek** [comment]
> MacOS handle the preferences with a cache system.
> Perhaps by restarting the Finder they had not had time to save themselves?

I don't know. Also, there is currently no way to know if the settings are saved or applied. (Nothing happens when the save button is clicked.)

**Comment by sbarex** [comment]
When you make a change on the settings, the red close window button show the dirty status. if the save is successful the dirty status will be reset.

**Comment by hazarek** [comment]
> When you make a change on the settings, the red close window button show the dirty status. if the save is successful the dirty status will be reset.

this is top secret. You should put a label that says "saved. or it can be a flash effect like TextEdit"

https://user-images.githubusercontent.com/36481442/103160374-5d1a0000-47e5-11eb-813f-1d7fb3d252f1.mov

**Comment by hazarek** [comment]
Also save menu always disabled
<img width="184" alt="Ekran Resmi 2020-12-27 01 44 55" src="https://user-images.githubusercontent.com/36481442/103160382-7a4ece80-47e5-11eb-9b6c-4f5390f6211a.png">

**Comment by sbarex** [comment]
ahah, yes it's not very intuitive.
The menu action is not linked to the action of the button... new release will fix it.

**Comment by relikd** [comment]
The changes are reflected even without a Finder restart but it takes more time. It was nearly one minute on my machine at one point. But like @sbarex said some caching issues. Maybe there is a way to tell macOS to force prune the cache?

**Comment by hazarek** [comment]
workarounds are making the plugin garbage. I guess sbarex doesn't like simplicity and functionality.

**Comment by relikd** [comment]
@hazarek thats not fair. The app is still very early stage. If you don't like how it works propose a PR to fix it. But don't badmouth the time and effort someone puts into this in their free time.

**Comment by hazarek** [comment]
i am graphic designer not apple developer. i can speak about design and concepts i can write simple markup languages (xml, html,css,markdown etc) and python. i am learning golang for hobby.

**Comment by hazarek** [comment]
> @hazarek thats not fair. The app is still very early stage. If you don't like how it works propose a PR to fix it. But don't badmouth the time and effort someone puts into this in their free time.

You are right sorry. I'm just so excited. @sbarex sorry. Thanks for the plugin.
