### ISSUE TITLE
README footnotes don't render on GitHub

### ISSUE THREAD

**Issue by orchetect** [sbarex/QLMarkdown#31]
_[minor cosmetic issue]_

In a possibly ironic twist, the `[^footnote]` marks in the [README.md](https://github.com/sbarex/QLMarkdown/blob/main/README.md) file don't render in the browser as jump links and just appear as plain text on the GitHub repo page displaying the README file.

I'm guessing this is a markdown feature not supported by GitHub.

**Comment by sbarex** [comment]
The app uses [`cmark-gfm`](https://github.com/github/cmark-gfm) that implement the footnotes support. But For the site github uses another engine that not handle the footnotes :man_shrugging:

**Comment by orchetect** [comment]
Yes not a big deal, just wanted to point out that the README.md that gets rendered on GitHub repo page may best be formatted using only markup that GitHub supports because that's where people will mainly be seeing it.

**Comment by hazarek** [comment]
I think this is important. the default theme and Markdown syntax follow Github's GFM.  Github visited by millions of people should have more priority than local markdown files.
