### ISSUE TITLE
License contradiction

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#33]
The about window does not comply with the GNU General Public License v3.0 license.

> Copyright © 2020 SBAREX. All rights reserved.

<img width="396" alt="about" src="https://user-images.githubusercontent.com/36481442/103426251-20754c80-4bc9-11eb-9979-b4adbc16d616.png">

**Comment by sbarex** [comment]
This is the default about panel made by Xcode. I will fix in next release.
