### ISSUE TITLE
Overwrite bug

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#35]
# 1
  <img width="288" alt="Ekran Resmi 2020-01-01 02 32 26" src="https://user-images.githubusercontent.com/36481442/103430906-a8fbe900-4bd9-11eb-8fc2-0d84fb0ee42b.png">

# 2
<img width="272" alt="Ekran Resmi 2020-01-01 02 31 46" src="https://user-images.githubusercontent.com/36481442/103430913-b2855100-4bd9-11eb-909a-46408c714f09.png">

# 3
<img width="266" alt="Ekran Resmi 2020-01-01 02 31 58" src="https://user-images.githubusercontent.com/36481442/103430920-c16c0380-4bd9-11eb-8c12-97e9ef646fbf.png">

**Comment by sbarex** [comment]
Fixed in next release.
