### ISSUE TITLE
bug on css emoji font

### ISSUE THREAD

**Issue by sbarex** [sbarex/QLMarkdown#39]
The document font is set to `-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji, Segoe UI Emoji;`.

In this way some emoji are rendered with system font and not the apple color. For example the heart.

<img width="114" alt="heart" src="https://user-images.githubusercontent.com/1948940/103474640-2bd19f00-4da6-11eb-93cc-c6bcd89bdd13.png">

Two solutions:
- encapusulte the emoji inside a `<span class="emoji">❤</span>` and customize the font for the class in the CSS
- change the document font to 'Apple Color Emoji, Segoe UI Emoji, -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif'. In this way I do not know if the are others unwanted effects.

@hazarek what do you think?

**Comment by hazarek** [comment]
@sbarex  I don't even know how it works with emojis, I use emoji very rarely. I have no idea. I guess the second option seems to be better.

**Comment by sbarex** [comment]
Latest commit to the emoji extension fix this bug without edit the CSS style.
