### ISSUE TITLE
dark highlight doesn't work

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#4]
<img width="523" alt="Ekran Resmi 2020-12-27 01 19 19" src="https://user-images.githubusercontent.com/36481442/103160227-4672a980-47e3-11eb-803f-2e5f67d9f1a2.png">
<img width="827" alt="Ekran Resmi 2020-12-27 01 18 22" src="https://user-images.githubusercontent.com/36481442/103160228-4a9ec700-47e3-11eb-822e-36ba88979918.png">

**Comment by sbarex** [comment]
Perhaps it is still due to problems saving preferences.

In reality, sharing preferences between application and extension should require code signing. However, the application is not signed...

To check the preferences, you can open the drop menu (…) near the style popou. Then chosse "open application support styles folder". The fineder will open the folder where store custom css. Going up of one or two parent folder there is the Preferences folder. Inside there is the plist file with the settings.

You cannot change this file (the settings cannot be customized editing the plist... cache problem...) but you can see if the values are saved.

**Comment by hazarek** [comment]
> Perhaps it is still due to problems saving preferences.
> 
> In reality, sharing preferences between application and extension should require code signing. However, the application is not signed...
> 
> To check the preferences, you can open the drop menu (…) near the style popou. Then chosse "open application support styles folder". The fineder will open the folder where store custom css. Going up of one or two parent folder there is the Preferences folder. Inside there is the plist file with the settings.
> 
> You cannot change this file (the settings cannot be customized editing the plist... cache problem...) but you can see if the values are saved.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>autolink</key>
	<true/>
	<key>checkbox</key>
	<false/>
	<key>customCSS</key>
	<string></string>
	<key>customCSS-override</key>
	<false/>
	<key>emoji</key>
	<true/>
	<key>emoji_image</key>
	<false/>
	<key>footnote</key>
	<false/>
	<key>guess-engine</key>
	<integer>0</integer>
	<key>hardbreak</key>
	<false/>
	<key>inlineimage</key>
	<true/>
	<key>mention</key>
	<false/>
	<key>nosoftbreak</key>
	<false/>
	<key>smartquote</key>
	<false/>
	<key>strikethrough</key>
	<true/>
	<key>strikethrough_doubletilde</key>
	<false/>
	<key>syntax</key>
	<true/>
	<key>syntax_dark_background</key>
	<string></string>
	<key>syntax_dark_theme</key>
	<string>atelier-dune</string>
	<key>syntax_font_name</key>
	<string></string>
	<key>syntax_font_size</key>
	<real>0.0</real>
	<key>syntax_light_background</key>
	<string></string>
	<key>syntax_light_theme</key>
	<string>summerfruit-dark</string>
	<key>syntax_line_numbers</key>
	<false/>
	<key>syntax_tabs</key>
	<integer>4</integer>
	<key>syntax_word_wrap</key>
	<integer>0</integer>
	<key>table</key>
	<true/>
	<key>tagfilter</key>
	<true/>
	<key>tasklist</key>
	<true/>
	<key>unsafeHTML</key>
	<false/>
	<key>validateUTF</key>
	<false/>
</dict>
</plist>
```
doesn't work

**Comment by relikd** [comment]
I think the light & dark theme you see above is only used for the code blocks. But here I have to add something. Some of the dark themes like `Base16 3024` are displayed in light colors instead of dark ones.

**Comment by sbarex** [comment]
I see there is a problem with the "base16" themes. This prevents the theme file from being found and the first available ("acid") is loaded in its place

**Comment by sbarex** [comment]
Fixed in last commit.
