### ISSUE TITLE
Scroll bar doesn't work

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#43]
scroll bar does not work. it moves the window instead of scrolling the page.
<img width="116" alt="Ekran Resmi 2021-01-04 00 05 37" src="https://user-images.githubusercontent.com/36481442/103488796-d090c280-4e20-11eb-9c15-e9893428ac9f.png">

**Comment by sbarex** [comment]
Yes, I know ... yet another big sur bug ... it also happens with other plugins, even if they don't use a webview.
I reported to apple ... no response.

**Comment by hazarek** [comment]
it's better to keep this issue open.

**Comment by sbarex** [comment]
If you want you can also make a report to Apple: https://feedbackassistant.apple.com.
