### ISSUE TITLE
Fragment links inside document broken

### ISSUE THREAD

**Issue by relikd** [sbarex/QLMarkdown#47]
Title is a bit misleading, not all of them are broken but some. Presumably due to the handling of special characters.

```
link to [section](#a-preamble)

### A) Preamble
...
```

Github is removing special characters before creating the title reflink label. In the case above the closing parenthesis. Though I don't know what the set of special characters is. But the example above does work on Github – just not in the preview.

**Comment by sbarex** [comment]
This bug was fixed in a previous commit. But I hadn't released the compiled version yet pending any other bugs to be fixed. I load it now (release 16).
