### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#48]
# 1
<img width="732" alt="Ekran Resmi 2021-01-17 02 49 48" src="https://user-images.githubusercontent.com/36481442/104827454-dd74d380-586e-11eb-882d-91420992941e.png">

# 2
<img width="437" alt="Ekran Resmi 2021-01-17 01 57 54" src="https://user-images.githubusercontent.com/36481442/104827461-fb423880-586e-11eb-92ae-895275184d6e.png">

**Comment by sbarex** [comment]
fixed
