### ISSUE TITLE
Error while preview

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#5]
<img width="838" alt="Ekran Resmi 2020-12-27 01 52 54" src="https://user-images.githubusercontent.com/36481442/103160457-753e4f00-47e6-11eb-97f7-c8f633ae074f.png">
QLMarkdown - Version 1.0 (3)

translation: There was an error in the org.sparex.QLMarkdown.QLExtension extension while previewing the document.

reproduction;

1.` git clone https://github.com/hazarek/go-md-turkce-kaynaklar`
2. preview go-md-turkce-kaynaklar/go-programlama-dili/02-bolum-1-on-egitim.md

**Comment by relikd** [comment]
Does this issue still appear in the latest beta? For me this warning appeared when the host app could not be found. For example if I put it in the trash bin. If you disable the QL plugin before deleting the app, it should be fixed.

**Comment by hazarek** [comment]
Version 1.0 (6)
It happens because of the syntax in the markdown file. but I could not determine which part it was. it was fixed when i deleted half of the file. I think it's markdown parsing error.

https://user-images.githubusercontent.com/36481442/103177772-572c2980-488e-11eb-9665-5f35184f2c64.mov

**Comment by sbarex** [comment]
> Version 1.0 (6)
> It happens because of the syntax in the markdown file. but I could not determine which part it was. it was fixed when i deleted half of the file. I think it's markdown parsing error.
> Ekran.Kaydi.2020-12-27.21.49.56.mov

If you want post the md file for a test

**Comment by hazarek** [comment]
> > Version 1.0 (6)
> > It happens because of the syntax in the markdown file. but I could not determine which part it was. it was fixed when i deleted half of the file. I think it's markdown parsing error.
> > Ekran.Kaydi.2020-12-27.21.49.56.mov
> 
> If you want post the md file for a test

reproduction;

1. git clone https://github.com/hazarek/go-md-turkce-kaynaklar
2. preview go-md-turkce-kaynaklar/go-programlama-dili/02-bolum-1-on-egitim.md

**Comment by relikd** [comment]
I tried it with all of the md files and none of them is breaking for me. Maybe it is a BigSur issue?

**Comment by hazarek** [comment]
> I tried it with all of the md files and none of them is breaking for me. Maybe it is a BigSur issue?

Interesting. what is your macos version.

**Comment by relikd** [comment]
> Interesting. what is your macos version.

10.15.7

**Comment by hazarek** [comment]
> > Interesting. what is your macos version.
> 
> 10.15.7

Probably because there have been major changes.

**Comment by hazarek** [comment]
@sbarex  i found reason of error. Broken image links. Crash occurs when trying to embed image that does not exist.

```
# Error test

![image bug test](./img/nonexist.png)

```

**Comment by relikd** [comment]
Just for reference, this is shown on my side (without crash)
<img width="140" src="https://user-images.githubusercontent.com/1321720/103220800-6f995400-4921-11eb-8caa-b54db4b5cb15.png">

**Comment by hazarek** [comment]
Also crash in App

https://user-images.githubusercontent.com/36481442/103221101-e559eb80-4932-11eb-9e4b-ceccb269f29b.mov

**Comment by sbarex** [comment]
Thanks for the debug. There is a bug about a null pointer. It will fix in next release. Sorry for the delay but I'm busy fixing the interface ;)

**Comment by sbarex** [comment]
Fixed in 1.0b7.
