### ISSUE TITLE
Clipboard doesn't work in Spotlight preview.

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#50]
I often use the Spotlight window to copy text to the clipboard. I can use clipboard for TXT, CSV files. but in QLMarkdown preview I can only copy the file path. (Press TAB key to open preview during Spotlight search.)

## TXT example
https://user-images.githubusercontent.com/36481442/105531850-fcee7f00-5cfa-11eb-9e02-9a14b0d283e3.mov

## MD example

https://user-images.githubusercontent.com/36481442/105532018-43dc7480-5cfb-11eb-9221-02b292ab5e8c.mov

**Comment by sbarex** [comment]
unfortunately there is no public api to manage the clipboard from a quick look preview

**Comment by hazarek** [comment]
> unfortunately there is no public api to manage the clipboard from a quick look preview

thanks.
