### ISSUE TITLE
Error while preview

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#51]
QLMarkdown - Version 1.0 (19)
similar error https://github.com/sbarex/QLMarkdown/issues/5. 

> There was an error in the org.sparex.QLMarkdown.QLExtension extension while previewing the document.

reproduction;

1. git clone https://github.com/mazznoer/colorgrad
2. preview colorgrad/README.md

**Comment by jeffThompson** [comment]
Just installed from the binary and got the same error

**Comment by sbarex** [comment]
It was a bug in interpreting emojis in heads. It should be fixed in release 20.
