### ISSUE TITLE
Auto-update not triggering

### ISSUE THREAD

**Issue by orchetect** [sbarex/QLMarkdown#53]
Every release that is pushed, running QLMarkdown.app does not trigger an auto-update. I have to manually go to the QLMarkdown menu and select 'Check for Updates'. Can we add the new version notification popup dialog to Sparkle here?

**Comment by sbarex** [comment]
Sparkle is normally set up to check for updates daily. Maybe at some point you turned off the search for updates?

In the new version just released (21) I added the preferences to manage the automatic update.

**Comment by orchetect** [comment]
I've had QLMarkdown installed on 3 different Macs since the first beta and for a while now, none of them were showing the new version window automatically.

**Comment by sbarex** [comment]
Updates are only searched when opening the main application and not when using the quicklook extension. I didn't want to slow down the preview by searching for updates.

**Comment by orchetect** [comment]
That's not what I'm saying. When running QLMarkdown.app, updates were never presented. You had to manually 'Check for Updates...' from the menu. I never expected the quicklook document preview to trigger update checks.
