### ISSUE TITLE
Slow performance.

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#57]
QLmarkdown 1.0 (21)

Model Identifier: MacBookPro13,3
Processor Name: Quad-Core Intel Core i7
Processor Speed: 2,7 GHz
Memory: 16 GB
SSD disk.

There is 1- 1.5 second delay for this README.md; https://github.com/mazznoer/colorgrad

https://user-images.githubusercontent.com/36481442/107069352-e82de300-67f2-11eb-9afd-0717988dfef3.mov

**Comment by sbarex** [comment]
I think the delay is due to the fact that the preview is only shown after the completion of the formatting of the html code (when the DOM is fully loaded).

In the next release the glitch for which the content is displayed smaller than the window for an instant should disappear.
