### ISSUE TITLE
Version confusion.

### ISSUE THREAD

**Issue by hazarek** [sbarex/QLMarkdown#58]
Github Release - > 1.0b21
About window -> 1.0 (21)
Finder info dialog -> 1.0
You're up to date - > 1.0

<img width="873" alt="Ekran Resmi 2021-02-05 20 49 14" src="https://user-images.githubusercontent.com/36481442/107070640-a736ce00-67f4-11eb-982f-2dfcf3222a0f.png">

Also these files do not have a version number.

<img width="210" alt="Ekran Resmi 2021-02-05 21 00 27" src="https://user-images.githubusercontent.com/36481442/107071193-67bcb180-67f5-11eb-90f8-740d68ecf7ab.png">

It should be that way.
QLMarkdown.1.0b21.zip

**Comment by sbarex** [comment]
Version is `1.0`. `21` is the build number.

I don't know a way to show build number in update windows :man_shrugging:.

**Comment by hazarek** [comment]
> Version is `1.0`. `21` is the build number.
> 
> I don't know a way to show build number in update windows 🤷‍♂️.

I thought it was beta. I guess it doesn't follow the semver rules.
https://semver.org/
