### ISSUE TITLE
Title for regular .md header (feature request)

### ISSUE THREAD

**Issue by PlainMartin** [sbarex/QLMarkdown#62]
Wonderful Quick Look extension; thank you for creating it!

It would be great if YAML blocks would also be rendered as a code block for regular (.md suffix) Markdown, not just .rmd. 

Thank you for looking into this.
<img width="501" alt="QL title" src="https://user-images.githubusercontent.com/304187/114386326-5eebb180-9b91-11eb-874a-9cc1230d6e80.png">

**Comment by sbarex** [comment]
On the new release (1.0b25) I have implemented this request.

**Comment by PlainMartin** [comment]
Thank you so much for implementing this. I am now in Markdown Preview Heaven. :)
