### ISSUE TITLE
[BUG] HTML codes not rendered

### ISSUE THREAD

**Issue by twio142** [sbarex/QLMarkdown#70]
### Content of document
![image](https://user-images.githubusercontent.com/64556708/124161220-6e4a0f00-da9d-11eb-88ff-c17d9ccd3393.png)

### Rendered in Typora
![image](https://user-images.githubusercontent.com/64556708/124161182-62f6e380-da9d-11eb-85f8-46a2b62bc5ed.png)

### In Quicklook
![image](https://user-images.githubusercontent.com/64556708/124160820-f380f400-da9c-11eb-80fb-f95b09a77b50.png)

**Comment by sbarex** [comment]
please attach a `.md` example code

**Comment by twio142** [comment]
[2.md](https://github.com/sbarex/QLMarkdown/files/6749757/2.md)

**Comment by sbarex** [comment]
Please check in the application that you have enabled "inline html" in the advanced settings.
<img width="922" alt="Schermata 2021-07-01 alle 18 56 39" src="https://user-images.githubusercontent.com/1948940/124162042-5d4dcd80-da9e-11eb-8ff4-a16730db8e0d.png">

**Comment by twio142** [comment]
It works now. Thanks a lot!
