### ISSUE TITLE
Processes open but never quit

### ISSUE THREAD

**Issue by subrandom** [sbarex/QLMarkdown#73]
This is on MacOS 12.0 beta, so I'm only adding it because I don't see it listed yet:

When quicklooking files, the Markdown QL Extension Web Content process is launched, once for every file viewed, but those processes never close. 

Although they do not appear to be using CPU each process is eating about 10MB of RAM. Today after doing a bunch of file maintenance I realized QLMarkdown was using 700+ MB of RAM

**Comment by sbarex** [comment]
I'll check when I can install the MacOS 12.

**Comment by sbarex** [comment]
Fixed on release 1.0.4 (29).
