### ISSUE TITLE
Notification of new UTI

### ISSUE THREAD

**Issue by davydka** [sbarex/QLMarkdown#77]
`dyn.ah62d4rv4ge8043a`

Per the installation instructions, this is a new UTI.

<img width="457" alt="Screen Shot 2021-10-26 at 11 56 55 PM" src="https://user-images.githubusercontent.com/1128500/139015723-c14d2e39-e5ef-4990-8699-4d5f870b6766.png">

Macbook Pro 14-inch
MacOs Monterey 12.0.1

**Comment by sbarex** [comment]
Fixed on release 1.0.4 (29).
