### ISSUE TITLE
Codeblock with HTML: Works fine in sbarex fork of QLMarkdown

### ISSUE THREAD

**Issue by porg** [sbarex/QLMarkdown#78]
@sbarex 
- thanks for providing a contemporary fork of the original QLMarkdown.
- Installation via brew was super convenient (on macOS 11.6 Big Sur)
- QuickLook of .md Markdown files worked instantly after having opened /Applications/QLMarkdown.app for the first time.

👍 And you fixed something which did not work in the old QLMarkdown:

# Bug of the original

![QLMarkdown chokes on codeblock with HTML](https://user-images.githubusercontent.com/737143/139538458-75a7be25-c443-499d-b95a-4c8fe51105b2.png)

# Fixed in your fork — Nice!

![QLMarkdown fork of sbarex handles all 3 codeblocks fine](https://user-images.githubusercontent.com/737143/139538452-526951f9-63aa-4057-835e-e2262dfb1327.png)

**Comment by sbarex** [comment]
Thanks!

In the readme I explained the reasons for certain display differences between my plugin and the github preview.

The latest version better recognizes the Javascript fenced block.
