### ISSUE TITLE
Adjust Font size

### ISSUE THREAD

**Issue by mikaeljagelid** [sbarex/QLMarkdown#79]

**Comment by mikaeljagelid** [comment]
Love the plugin, but I find the font size too big in relation to the system text size. Is it possible to configure the font size in any way?

**Comment by sbarex** [comment]
You can create a custom css style with a contents like this:
```css
body {
    font-size: 8pt;
}
```

Then, from the Theme drop-down, choose `Import` and select your css file.
A new option will appear to the right of the Theme drop-down menu which needs to be set to `Extend Default`.

**Comment by hazarek** [comment]
> Love the plugin, but I find the font size too big in relation to the system text size. Is it possible to configure the font size in any way?

Hi, All font sizes are exactly the same as the Markdown view of github.com  site
