### ISSUE TITLE
Image embedding sadly skipped if filename contains whitespace

### ISSUE THREAD

**Issue by porg** [sbarex/QLMarkdown#80]
## Rendering Result in [QLMarkdown](https://github.com/sbarex/QLMarkdown/) vs. [Macdown](https://github.com/MacDownApp/macdown)
![Embedded image with whitespace in file name are not rendered but shown as raw markup text](https://user-images.githubusercontent.com/737143/141841772-76b351e9-5b39-453a-9a9f-98fffb673247.png)

## Reproduction
- Create a `.md? file
- In the markdown source embed an image with `![](file name having whitespace.png)`
  - That is a relative link to an image file on the same hierarchy as the markdown file with whitespace in the file name.
- Anywhere image placement is allowed, i.e. in the body or in a table.

### Sample

```
## Images

### Filename without whitespace

![](1.png)

### Filename with whitespace

![](1 b.png)

## Table

| Column One     | Column Two    |
| :---           | :---          |
| Text 1         | Text 2        |
| ![](1.png)     | ![](1 b.png)  |
| ![](1.png)     | ![](1.png)    |
| ![](1 b.png)   | ![](1 b.png)  |
```

## Expected
- The image thumbnail/preview is shown regardless if the filename contains whitespace or not.
  - Everything between the round brackets is considered the filepath.
  - Round brackets in filenames need escaping of course.
  - Whitespace is escaped by the system automatically
  - If it does not start with a slash it is considered a relative path.
- [Macdown](https://github.com/MacDownApp/macdown) handles it like that.

## Actual
- Images containing whitespace in their filename are skipped and instead the raw markup text is shown.

**Comment by sbarex** [comment]
White space is not allowed inside url, they must be encoded as %20.
See the [markdown link specification](https://spec.commonmark.org/0.21/#link-destination):
> ... a nonempty sequence of characters that does not include ASCII space or control characters...

**Comment by porg** [comment]
Thanks for quoting the specification.

Could QLMarkdown nevertheless consider this as a convenience option if it does not harm/complicate syntax parsing too much?

The guys from MacDown have also added this convenience option as can be seen on the screenshot.

**Comment by porg** [comment]
I just remind that markdown's goal was an easily human readable/writeable markup language.
Having to transform ` ` to `%20` everywhere contradicts that goal IMHO.

**Comment by sbarex** [comment]
Markdown was born to be a simple language, then unfortunately, perhaps also due to the absence of a rigid syntax, it has branched into a myriad of flavors with different functionalities and extensions. 

My application uses the engine [cmark-gfm](https://github.com/github/cmark-gfm) that is a fork from commonmark. Macdown uses a different engine ([hoedown](https://github.com/hoedown/hoedown)). 

I have no intention of intervening on the engine code (I am not an expert C developer) to change the standard behavior.
If cmark-gfm were to add this feature, I will be happy to support it in my app.

**Comment by porg** [comment]
* Switching to hoedown: Neither an option to me as a layman (QLMarkdown overally looks/feels better than Macdown) and I guess also not to you.
* So my remaining option is to lobby for this feature at [cmark-gfm](https://github.com/github/cmark-gfm), right?

**Comment by sbarex** [comment]
When I started developing the app I didn't do a full research on what markdown engines existed. I chose cmark-gfm because it is maintained by github, although I later discovered that it is not used for managing github pages !

**Comment by porg** [comment]
@sbarex as you can see by the cross-project-link I inquired over as cmark-gfm. Let's see what they make of it.

**Comment by porg** [comment]
## Closing as WONTFIX
- @Lemmingh informed me that [URIs with spaces within round brackets would lead to ambiguity](https://github.com/github/cmark-gfm/issues/247#issuecomment-1134547686) and that I can simply wrap filenames containing spaces within rounded AND angled brackets, which the Markdown syntax already supports.
- Markdown `[link](</my uri>)` produces HTML `<p><a href="/my%20uri">link</a></p>` as shown in https://spec.commonmark.org/0.30/#example-488
- I tested this and QLMarkdown via its rendering engine [cmark-gfm](https://github.com/github/cmark-gfm/) supports this syntax just fine. See screenshots below.


## Markdown Specification

https://spec.commonmark.org/0.30/#links

> A link contains link text (the visible text), a link destination (the URI that is the link destination), and optionally a link title. There are two basic kinds of links in Markdown. In inline links the destination and title are given immediately after the link text. In reference links the destination and title are defined elsewhere in the document.

> A link text consists of a sequence of zero or more inline elements enclosed by square brackets ([ and ]).

> […]

> A link destination consists of either
>
> - a sequence of zero or more characters between an opening < and a closing > that contains no line endings or unescaped < or > characters, or
> 
> - a nonempty sequence of characters that does not start with <, does not include ASCII control characters or space character, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.

> […]

> An inline link consists of a link text followed immediately by a left parenthesis (, an optional link destination, an optional link title, and a right parenthesis ). 

## Screenshot

![QLMarkdown renders filename with spaces if within angled and rounded brackets](https://user-images.githubusercontent.com/737143/169820594-99c42cd4-545b-4adc-9765-071c0cb9c578.png)

**Comment by sbarex** [comment]
Thanks, I didn't know the syntax of angle brackets!
