### ISSUE TITLE
QLMarkdown is overridden by other quicklook apps 

### ISSUE THREAD

**Issue by Ken0sis** [sbarex/QLMarkdown#88]
From version 1.0.3 onward, QLMarkdown doesn't run on my MacOS (I'm on Monterey) because it will use another quicklook app like iPreview instead.  I use apps like iPreview to preview Jupyter notebooks; however, it also provides preview for markdown as well, and so my MacOS has two choices for quicklook.  My preference is to prioritize using QLMarkdown for markdown files, and this works only in version 1.0.2 and below.

I really want to be able to use QLMarkdown and have it be the preferred quicklook.

**Comment by sbarex** [comment]
The  QLMarkdown version 1.0.3 shouldn't have changed the quick look behavior. Perhaps at that time you also installed / updated iPreview?

Apple does not provide an effective system for choosing which program to use to manage previews. In the `System preferences` > `extensions` > `quick look` try dragging QLMarkdown to the top of the list.

**Comment by Ken0sis** [comment]
Thanks.  Actually, moving QLMarkdown to the top of the quick look extension list does allow me to reprioritize which extension takes effect whenever there's a conflict of multiple quicklook.
