### ISSUE TITLE
Unexpected crashing when other applications try to preview markdown

### ISSUE THREAD

**Issue by Ken0sis** [sbarex/QLMarkdown#89]
I'm not sure if this is a problem with QLMarkdown, but it's causing the application to crash so I'm reporting it here.  I use an application called Foxtrot Search, and it provides preview to markdown search results using its own text parser.  The problem is whenever I use Foxtrot to preview a markdown file, I get a message saying QLMarkdown crashes.  Attached is example of crash report

Translated Report (Full Report Below)
-------------------------------------

Process:               qlmanage [26105]
Path:                  /System/Library/Frameworks/QuickLook.framework/Versions/A/Resources/qlmanage.app/Contents/MacOS/qlmanage
Identifier:            com.apple.quicklook.qlmanage
Version:               1.0 (1)
Build Info:            QuickLook_executables-950001000000000~63
Code Type:             ARM-64 (Native)
Parent Process:        FoxTrot Professional Search [20039]
Responsible:           FoxTrot Professional Search [20039]
User ID:               501

Date/Time:             2021-12-27 22:09:49.0084 -0800
OS Version:            macOS 12.1 (21C52)
Report Version:        12
Anonymous UUID:        2801199E-A7C3-F677-6C3D-EE1429DE7830

Sleep/Wake UUID:       D420CEF7-2691-4148-8432-FF6FA0D1515E

Time Awake Since Boot: 46000 seconds
Time Since Wake:       3598 seconds

System Integrity Protection: enabled

Crashed Thread:        2  Dispatch queue: com.apple.quicklook.qlextension.request

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: key cannot be nil'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 0:
0   CoreFoundation                      0x00000001aaa501cc __exceptionPreprocess + 240
1   libobjc.A.dylib                     0x00000001aa7a17b8 objc_exception_throw + 60
2   CoreFoundation                      0x00000001aab20488 -[__NSCFString characterAtIndex:].cold.1 + 0
3   CoreFoundation                      0x00000001aab2d260 -[__NSDictionaryM setObject:forKey:].cold.2 + 0
4   CoreFoundation                      0x00000001aa989628 -[__NSDictionaryM setObject:forKey:] + 896
5   ExtensionFoundation                 0x00000001bd157658 -[EXConcreteExtension makeExtensionContextAndXPCConnectionForRequest:error:] + 408
6   ExtensionFoundation                 0x00000001bd159b90 -[EXConcreteExtension _beginExtensionRequest:error:] + 376
7   ExtensionFoundation                 0x00000001bd158eb8 -[EXConcreteExtension beginExtensionRequestWithOptions:inputItems:error:] + 136
8   QuickLookSupport                    0x00000001c8468134 -[QLExtension _setupConnectionIfNeededWithCompletionHandler:] + 196
9   QuickLookSupport                    0x00000001c8468e00 __53-[QLExtension extensionContextWithCompletionHandler:]_block_invoke + 120
10  libdispatch.dylib                   0x00000001aa744e60 _dispatch_call_block_and_release + 32
11  libdispatch.dylib                   0x00000001aa746bac _dispatch_client_callout + 20
12  libdispatch.dylib                   0x00000001aa74e330 _dispatch_lane_serial_drain + 672
13  libdispatch.dylib                   0x00000001aa74eea4 _dispatch_lane_invoke + 392
14  libdispatch.dylib                   0x00000001aa759708 _dispatch_workloop_worker_thread + 656
15  libsystem_pthread.dylib             0x00000001aa901304 _pthread_wqthread + 288
16  libsystem_pthread.dylib             0x00000001aa900018 start_wqthread + 8

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1aa8c9954 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1aa8c9d00 mach_msg + 76
2   CoreFoundation                	       0x1aa9d0ed8 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1aa9cf390 __CFRunLoopRun + 1212
4   CoreFoundation                	       0x1aa9ce734 CFRunLoopRunSpecific + 600
5   Foundation                    	       0x1ab8a3da0 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6   Foundation                    	       0x1ab9338a0 -[NSRunLoop(NSRunLoop) run] + 92
7   qlmanage                      	       0x10079caf0 0x100794000 + 35568
8   qlmanage                      	       0x1007a0df0 0x100794000 + 52720
9   dyld                          	       0x100a190f4 start + 520

Thread 1:
0   libsystem_pthread.dylib       	       0x1aa900010 start_wqthread + 0

Thread 2 Crashed::  Dispatch queue: com.apple.quicklook.qlextension.request
0   libsystem_kernel.dylib        	       0x1aa8d19b8 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1aa904eb0 pthread_kill + 288
2   libsystem_c.dylib             	       0x1aa842314 abort + 164
3   libc++abi.dylib               	       0x1aa8c1b50 abort_message + 132
4   libc++abi.dylib               	       0x1aa8b2f64 demangling_terminate_handler() + 332
5   libobjc.A.dylib               	       0x1aa7aa140 _objc_terminate() + 144
6   libc++abi.dylib               	       0x1aa8c0ee4 std::__terminate(void (*)()) + 20
7   libc++abi.dylib               	       0x1aa8c0e80 std::terminate() + 64
8   libdispatch.dylib             	       0x1aa746bc0 _dispatch_client_callout + 40
9   libdispatch.dylib             	       0x1aa74e330 _dispatch_lane_serial_drain + 672
10  libdispatch.dylib             	       0x1aa74eea4 _dispatch_lane_invoke + 392
11  libdispatch.dylib             	       0x1aa759708 _dispatch_workloop_worker_thread + 656
12  libsystem_pthread.dylib       	       0x1aa901304 _pthread_wqthread + 288
13  libsystem_pthread.dylib       	       0x1aa900018 start_wqthread + 8

Thread 3:
0   libsystem_kernel.dylib        	       0x1aa8c9954 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1aa8c9d00 mach_msg + 76
2   CoreFoundation                	       0x1aa9d0ed8 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1aa9cf390 __CFRunLoopRun + 1212
4   CoreFoundation                	       0x1aa9ce734 CFRunLoopRunSpecific + 600
5   qlmanage                      	       0x1007a31b4 0x100794000 + 61876
6   Foundation                    	       0x1ab89c2e8 __NSThread__start__ + 808
7   libsystem_pthread.dylib       	       0x1aa905240 _pthread_start + 148
8   libsystem_pthread.dylib       	       0x1aa900024 thread_start + 8

Thread 4:
0   libsystem_pthread.dylib       	       0x1aa900010 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x1aa900010 start_wqthread + 0

Thread 2 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x00000001aa8c50ad   x5: 0x000000016f77e440   x6: 0x000000000000006e   x7: 0x0000000000000300
    x8: 0xe17256bc2263f60a   x9: 0xe17256bd4d14060a  x10: 0x0000000000000002  x11: 0x000000000000000b
   x12: 0x000000008b63301b  x13: 0x000000000b633000  x14: 0x0000000000000010  x15: 0x0000000000000002
   x16: 0x0000000000000148  x17: 0x00000002050e3530  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x000000016f77f000  x21: 0x000000000000280b  x22: 0x0000000000000000  x23: 0x000000016f77f0e0
   x24: 0x000060000035aee8  x25: 0x0000000000000000  x26: 0x0000000000000114  x27: 0x0000000000000000
   x28: 0x000060000384ccc0   fp: 0x000000016f77e3b0   lr: 0x00000001aa904eb0
    sp: 0x000000016f77e390   pc: 0x00000001aa8d19b8 cpsr: 0x40001000
   far: 0x000000012283d998  esr: 0x56000080  Address size fault

Binary Images:
       0x1aa8c8000 -        0x1aa8fdfff libsystem_kernel.dylib (*) <c8b3081a-5081-3a99-bbe3-01413de444c6> /usr/lib/system/libsystem_kernel.dylib
       0x1aa94c000 -        0x1aae8ffff com.apple.CoreFoundation (6.9) <f5ea9592-4ef9-3d35-b23d-5c21283acc52> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1ab840000 -        0x1abc2dfff com.apple.Foundation (6.9) <cd7cdf11-986e-3754-8011-e628c3be8380> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x100794000 -        0x1007b3fff com.apple.quicklook.qlmanage (1.0) <307fc185-cd22-3f1d-bd26-d2c37b3d73e0> /System/Library/Frameworks/QuickLook.framework/Versions/A/Resources/qlmanage.app/Contents/MacOS/qlmanage
       0x100a14000 -        0x100a73fff dyld (*) <7e92b284-4b90-3b68-b31a-3ddc4c0e8d40> /usr/lib/dyld
       0x1aa8fe000 -        0x1aa90afff libsystem_pthread.dylib (*) <ed328b18-eeef-3b15-8858-798b19b0c2cd> /usr/lib/system/libsystem_pthread.dylib
       0x1aa7c9000 -        0x1aa849fff libsystem_c.dylib (*) <00fc01c7-36bc-3193-86a3-5c03046b45fb> /usr/lib/system/libsystem_c.dylib
       0x1aa8ae000 -        0x1aa8c7fff libc++abi.dylib (*) <540088b6-cc81-381f-901c-5632f4a73c45> /usr/lib/libc++abi.dylib
       0x1aa78a000 -        0x1aa7c5fff libobjc.A.dylib (*) <8a930227-747e-381f-bb29-2dfe267a84f7> /usr/lib/libobjc.A.dylib
       0x1aa743000 -        0x1aa789fff libdispatch.dylib (*) <3a9e9a1e-72b6-3f66-aa17-d955384c1a39> /usr/lib/system/libdispatch.dylib
       0x1bd152000 -        0x1bd19dfff com.apple.ExtensionFoundation (34.5) <5aa094d3-f9cf-37c4-a1f3-97da2ec94239> /System/Library/PrivateFrameworks/ExtensionFoundation.framework/Versions/A/ExtensionFoundation
       0x1c844f000 -        0x1c847cfff com.apple.quicklook.QuickLookSupport (1.0) <f87f6086-f883-3a72-9062-b0f732812571> /System/Library/PrivateFrameworks/QuickLookSupport.framework/Versions/A/QuickLookSupport

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=844.9M resident=0K(0%) swapped_out_or_unallocated=844.9M(100%)
Writable regions: Total=816.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=816.1M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           181.2M       26 
MALLOC guard page                   96K        5 
MALLOC_MEDIUM (reserved)         240.0M        2         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.1M        6 
Stack                             10.6M        6 
VM_ALLOCATE                        1.0G        2 
__AUTH                            1916K      174 
__AUTH_CONST                      11.4M      316 
__DATA                            8653K      303 
__DATA_CONST                      11.7M      318 
__DATA_DIRTY                       928K      118 
__FONT_DATA                          4K        1 
__LINKEDIT                       575.7M        3 
__OBJC_CONST                      1850K      146 
__OBJC_RO                         82.0M        1 
__OBJC_RW                         3104K        1 
__TEXT                           269.1M      330 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
mapped file                       34.5M        4 
shared memory                     1136K        7 
===========                     =======  ======= 
TOTAL                              2.8G     1774 
TOTAL, minus reserved VM space     2.2G     1774 

-----------
Full Report
-----------

{"app_name":"qlmanage","timestamp":"2021-12-27 22:09:49.00 -0800","app_version":"1.0","slice_uuid":"307fc185-cd22-3f1d-bd26-d2c37b3d73e0","build_version":"1","platform":1,"bundleID":"com.apple.quicklook.qlmanage","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.1 (21C52)","incident_id":"1BF691FE-289D-4384-A907-8661D1BE0F78","name":"qlmanage"}
{
  "uptime" : 46000,
  "procLaunch" : "2021-12-27 22:09:48.8674 -0800",
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Macmini9,1",
  "procStartAbsTime" : 1111003099251,
  "coalitionID" : 8112,
  "osVersion" : {
    "train" : "macOS 12.1",
    "build" : "21C52",
    "releaseType" : "User"
  },
  "captureTime" : "2021-12-27 22:09:49.0084 -0800",
  "incident" : "1BF691FE-289D-4384-A907-8661D1BE0F78",
  "bug_type" : "309",
  "pid" : 26105,
  "procExitAbsTime" : 1111006467349,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "qlmanage",
  "procPath" : "\/System\/Library\/Frameworks\/QuickLook.framework\/Versions\/A\/Resources\/qlmanage.app\/Contents\/MacOS\/qlmanage",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0","CFBundleVersion":"1","CFBundleIdentifier":"com.apple.quicklook.qlmanage"},
  "buildInfo" : {"ProjectName":"QuickLook_executables","SourceVersion":"950001000000000","BuildVersion":"63"},
  "storeInfo" : {"deviceIdentifierForVendor":"2D1BC12E-DF46-5D62-9F9D-B04FD2BE0355","thirdParty":true},
  "parentProc" : "FoxTrot Professional Search",
  "parentPid" : 20039,
  "coalitionName" : "com.ctmdev.FoxTrotPro",
  "crashReporterKey" : "2801199E-A7C3-F677-6C3D-EE1429DE7830",
  "responsiblePid" : 20039,
  "responsibleProc" : "FoxTrot Professional Search",
  "wakeTime" : 3598,
  "sleepWakeUUID" : "D420CEF7-2691-4148-8432-FF6FA0D1515E",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "asi" : {"CoreFoundation":["*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: key cannot be nil'"],"libsystem_c.dylib":["abort() called"],"libc++abi.dylib":["terminating with uncaught exception of type NSException"]},
  "asiBacktraces" : ["0   CoreFoundation                      0x00000001aaa501cc __exceptionPreprocess + 240\n1   libobjc.A.dylib                     0x00000001aa7a17b8 objc_exception_throw + 60\n2   CoreFoundation                      0x00000001aab20488 -[__NSCFString characterAtIndex:].cold.1 + 0\n3   CoreFoundation                      0x00000001aab2d260 -[__NSDictionaryM setObject:forKey:].cold.2 + 0\n4   CoreFoundation                      0x00000001aa989628 -[__NSDictionaryM setObject:forKey:] + 896\n5   ExtensionFoundation                 0x00000001bd157658 -[EXConcreteExtension makeExtensionContextAndXPCConnectionForRequest:error:] + 408\n6   ExtensionFoundation                 0x00000001bd159b90 -[EXConcreteExtension _beginExtensionRequest:error:] + 376\n7   ExtensionFoundation                 0x00000001bd158eb8 -[EXConcreteExtension beginExtensionRequestWithOptions:inputItems:error:] + 136\n8   QuickLookSupport                    0x00000001c8468134 -[QLExtension _setupConnectionIfNeededWithCompletionHandler:] + 196\n9   QuickLookSupport                    0x00000001c8468e00 __53-[QLExtension extensionContextWithCompletionHandler:]_block_invoke + 120\n10  libdispatch.dylib                   0x00000001aa744e60 _dispatch_call_block_and_release + 32\n11  libdispatch.dylib                   0x00000001aa746bac _dispatch_client_callout + 20\n12  libdispatch.dylib                   0x00000001aa74e330 _dispatch_lane_serial_drain + 672\n13  libdispatch.dylib                   0x00000001aa74eea4 _dispatch_lane_invoke + 392\n14  libdispatch.dylib                   0x00000001aa759708 _dispatch_workloop_worker_thread + 656\n15  libsystem_pthread.dylib             0x00000001aa901304 _pthread_wqthread + 288\n16  libsystem_pthread.dylib             0x00000001aa900018 start_wqthread + 8"],
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "lastExceptionBacktrace" : [{"imageOffset":1065400,"symbol":"__exceptionPreprocess","symbolLocation":220,"imageIndex":1},{"imageOffset":96184,"symbol":"objc_exception_throw","symbolLocation":60,"imageIndex":8},{"imageOffset":1918088,"symbol":"-[__NSCFString characterAtIndex:].cold.1","symbolLocation":0,"imageIndex":1},{"imageOffset":1970784,"symbol":"-[__NSDictionaryM setObject:forKey:].cold.2","symbolLocation":0,"imageIndex":1},{"imageOffset":251432,"symbol":"-[__NSDictionaryM setObject:forKey:]","symbolLocation":896,"imageIndex":1},{"imageOffset":22104,"symbol":"-[EXConcreteExtension makeExtensionContextAndXPCConnectionForRequest:error:]","symbolLocation":408,"imageIndex":10},{"imageOffset":31632,"symbol":"-[EXConcreteExtension _beginExtensionRequest:error:]","symbolLocation":376,"imageIndex":10},{"imageOffset":28344,"symbol":"-[EXConcreteExtension beginExtensionRequestWithOptions:inputItems:error:]","symbolLocation":136,"imageIndex":10},{"imageOffset":102708,"symbol":"-[QLExtension _setupConnectionIfNeededWithCompletionHandler:]","symbolLocation":196,"imageIndex":11},{"imageOffset":105984,"symbol":"__53-[QLExtension extensionContextWithCompletionHandler:]_block_invoke","symbolLocation":120,"imageIndex":11},{"imageOffset":7776,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":9},{"imageOffset":15276,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":9},{"imageOffset":45872,"symbol":"_dispatch_lane_serial_drain","symbolLocation":672,"imageIndex":9},{"imageOffset":48804,"symbol":"_dispatch_lane_invoke","symbolLocation":392,"imageIndex":9},{"imageOffset":91912,"symbol":"_dispatch_workloop_worker_thread","symbolLocation":656,"imageIndex":9},{"imageOffset":13060,"symbol":"_pthread_wqthread","symbolLocation":288,"imageIndex":5},{"imageOffset":8216,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":5}],
  "faultingThread" : 2,
  "threads" : [{"id":616047,"queue":"com.apple.main-thread","frames":[{"imageOffset":6484,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":7424,"symbol":"mach_msg","symbolLocation":76,"imageIndex":0},{"imageOffset":544472,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":1},{"imageOffset":537488,"symbol":"__CFRunLoopRun","symbolLocation":1212,"imageIndex":1},{"imageOffset":534324,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":1},{"imageOffset":408992,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":236,"imageIndex":2},{"imageOffset":997536,"symbol":"-[NSRunLoop(NSRunLoop) run]","symbolLocation":92,"imageIndex":2},{"imageOffset":35568,"imageIndex":3},{"imageOffset":52720,"imageIndex":3},{"imageOffset":20724,"symbol":"start","symbolLocation":520,"imageIndex":4}]},{"id":616048,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"triggered":true,"id":616049,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":7156289709},{"value":6165095488},{"value":110},{"value":768},{"value":16245142171909617162},{"value":16245142176920765962},{"value":2},{"value":11},{"value":2338533403},{"value":191049728},{"value":16},{"value":2},{"value":328},{"value":8674751792},{"value":0},{"value":6},{"value":6165098496},{"value":10251},{"value":0},{"value":6165098720},{"value":105553119784680},{"value":0},{"value":276},{"value":0},{"value":105553175301312}],"flavor":"ARM_THREAD_STATE64","lr":{"value":7156551344},"cpsr":{"value":1073745920},"fp":{"value":6165095344},"sp":{"value":6165095312},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":7156341176,"matchesCrashFrame":1},"far":{"value":4874033560}},"queue":"com.apple.quicklook.qlextension.request","frames":[{"imageOffset":39352,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":0},{"imageOffset":28336,"symbol":"pthread_kill","symbolLocation":288,"imageIndex":5},{"imageOffset":496404,"symbol":"abort","symbolLocation":164,"imageIndex":6},{"imageOffset":80720,"symbol":"abort_message","symbolLocation":132,"imageIndex":7},{"imageOffset":20324,"symbol":"demangling_terminate_handler()","symbolLocation":332,"imageIndex":7},{"imageOffset":131392,"symbol":"_objc_terminate()","symbolLocation":144,"imageIndex":8},{"imageOffset":77540,"symbol":"std::__terminate(void (*)())","symbolLocation":20,"imageIndex":7},{"imageOffset":77440,"symbol":"std::terminate()","symbolLocation":64,"imageIndex":7},{"imageOffset":15296,"symbol":"_dispatch_client_callout","symbolLocation":40,"imageIndex":9},{"imageOffset":45872,"symbol":"_dispatch_lane_serial_drain","symbolLocation":672,"imageIndex":9},{"imageOffset":48804,"symbol":"_dispatch_lane_invoke","symbolLocation":392,"imageIndex":9},{"imageOffset":91912,"symbol":"_dispatch_workloop_worker_thread","symbolLocation":656,"imageIndex":9},{"imageOffset":13060,"symbol":"_pthread_wqthread","symbolLocation":288,"imageIndex":5},{"imageOffset":8216,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":5}]},{"id":616050,"frames":[{"imageOffset":6484,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":7424,"symbol":"mach_msg","symbolLocation":76,"imageIndex":0},{"imageOffset":544472,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":1},{"imageOffset":537488,"symbol":"__CFRunLoopRun","symbolLocation":1212,"imageIndex":1},{"imageOffset":534324,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":1},{"imageOffset":61876,"imageIndex":3},{"imageOffset":377576,"symbol":"__NSThread__start__","symbolLocation":808,"imageIndex":2},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":5},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":5}]},{"id":616051,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":616052,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7156301824,
    "size" : 221184,
    "uuid" : "c8b3081a-5081-3a99-bbe3-01413de444c6",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7156842496,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5521408,
    "uuid" : "f5ea9592-4ef9-3d35-b23d-5c21283acc52",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1856.105"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7172521984,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 4120576,
    "uuid" : "cd7cdf11-986e-3754-8011-e628c3be8380",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1856.105"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4302913536,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.quicklook.qlmanage",
    "size" : 131072,
    "uuid" : "307fc185-cd22-3f1d-bd26-d2c37b3d73e0",
    "path" : "\/System\/Library\/Frameworks\/QuickLook.framework\/Versions\/A\/Resources\/qlmanage.app\/Contents\/MacOS\/qlmanage",
    "name" : "qlmanage",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4305534976,
    "size" : 393216,
    "uuid" : "7e92b284-4b90-3b68-b31a-3ddc4c0e8d40",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7156523008,
    "size" : 53248,
    "uuid" : "ed328b18-eeef-3b15-8858-798b19b0c2cd",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7155257344,
    "size" : 528384,
    "uuid" : "00fc01c7-36bc-3193-86a3-5c03046b45fb",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7156195328,
    "size" : 106496,
    "uuid" : "540088b6-cc81-381f-901c-5632f4a73c45",
    "path" : "\/usr\/lib\/libc++abi.dylib",
    "name" : "libc++abi.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7154999296,
    "size" : 245760,
    "uuid" : "8a930227-747e-381f-bb29-2dfe267a84f7",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7154708480,
    "size" : 290816,
    "uuid" : "3a9e9a1e-72b6-3f66-aa17-d955384c1a39",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7467245568,
    "CFBundleShortVersionString" : "34.5",
    "CFBundleIdentifier" : "com.apple.ExtensionFoundation",
    "size" : 311296,
    "uuid" : "5aa094d3-f9cf-37c4-a1f3-97da2ec94239",
    "path" : "\/System\/Library\/PrivateFrameworks\/ExtensionFoundation.framework\/Versions\/A\/ExtensionFoundation",
    "name" : "ExtensionFoundation",
    "CFBundleVersion" : "34.5"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7654928384,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.quicklook.QuickLookSupport",
    "size" : 188416,
    "uuid" : "f87f6086-f883-3a72-9062-b0f732812571",
    "path" : "\/System\/Library\/PrivateFrameworks\/QuickLookSupport.framework\/Versions\/A\/QuickLookSupport",
    "name" : "QuickLookSupport",
    "CFBundleVersion" : "161"
  }
],
  "sharedCache" : {
  "base" : 7153352704,
  "size" : 3089596416,
  "uuid" : "66c33c62-48a9-31e5-b8b5-7a71c9760d07"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=844.9M resident=0K(0%) swapped_out_or_unallocated=844.9M(100%)\nWritable regions: Total=816.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=816.1M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           181.2M       26 \nMALLOC guard page                   96K        5 \nMALLOC_MEDIUM (reserved)         240.0M        2         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.1M        6 \nStack                             10.6M        6 \nVM_ALLOCATE                        1.0G        2 \n__AUTH                            1916K      174 \n__AUTH_CONST                      11.4M      316 \n__DATA                            8653K      303 \n__DATA_CONST                      11.7M      318 \n__DATA_DIRTY                       928K      118 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       575.7M        3 \n__OBJC_CONST                      1850K      146 \n__OBJC_RO                         82.0M        1 \n__OBJC_RW                         3104K        1 \n__TEXT                           269.1M      330 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nmapped file                       34.5M        4 \nshared memory                     1136K        7 \n===========                     =======  ======= \nTOTAL                              2.8G     1774 \nTOTAL, minus reserved VM space     2.2G     1774 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.quicklook.qlextension.request"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000196
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "61c11dcd2cb6041dc630dc63"
      },
      "deploymentId" : 240000357
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000090
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61a80a438feb033580c2778b"
      },
      "deploymentId" : 240000290
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    }
  ],
  "experiments" : [

  ]
}
}

Model: Macmini9,1, BootROM 7429.61.2, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: LG Ultra HD, 6016 x 3384, Main, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Oct 26 2021 16:10:41 version 18.20.310.15.7.8.120 FWID 01-5d6c3867
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
USB Device: USB31Bus
USB Device: USB3.0 Hub
USB Device: Cam Link 4K
USB Device: USB 10/100/1000 LAN
USB Device: USB2.0 Hub
USB Device: USB 2.0 Hub
USB Device: USB Billboard Device
USB Device: USB31Bus
USB Device: 4-Port USB 2.0 Hub
USB Device: 4-Port USB 2.0 Hub
USB Device: USB Receiver
USB Device: CORSAIR K63 Wireless USB Receiver
USB Device: BillBoard Device
USB Device: USB30Bus
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.

**Comment by sbarex** [comment]
I continue to have evidence that code compiled for arm is much more stricter in error handling than Intel code!

Try release 1.0.10.
Thanks.

**Comment by Ken0sis** [comment]
Thanks.  Seems to have fixed it?  I'm closing this issue for now and will re-open if issue comes back.  Thanks again.
