### ISSUE TITLE
Cannot import custom code syntax

### ISSUE THREAD

**Issue by danielcs88** [sbarex/QLMarkdown#92]
I am attempting to import custom code syntax themes to no success. I suspect that it might be that QLMarkdown does not have enough permissions perhaps to run.

![QLMarkdown](https://user-images.githubusercontent.com/13838845/150474793-efb4ddf4-19a8-4b87-add5-48ddfd4e1f29.gif)
.

Running on MacOS Silicon

**Comment by sbarex** [comment]
Sorry, but most of the color scheme editor features have never been implemented (probably not that useful after all). However I will try to implement it.

**Comment by sbarex** [comment]
I hope I have implemented all the missing code on the release 1.0.11 (36).

**Comment by danielcs88** [comment]
Thank you for the reply and your efforts!!!

**Comment by danielcs88** [comment]
**Working flawlessly**!

![image](https://user-images.githubusercontent.com/13838845/151919426-7a8a76aa-4be8-4fb7-a39a-bb4be3a52273.png)
