### ISSUE TITLE
The settings panel/editor doesn't open files thrown at it by the OS

### ISSUE THREAD

**Issue by bvandergiessen** [sbarex/QLMarkdown#93]
Thanks for this wonderful tool. I installed it for its QuickLook plugin, but actually the "Settings" editor itself is quite good and renders beautifully. Its exported HTML works very well in the browser.

Obviously it is meant as a settings panel, not an editor, but... why not add a menu item to save the Markdown file.

Probably for the same reason of not being meant as an editor, there is something strange about the opening of files. With <kbd>⌘</kbd>+<kbd>O</kbd>, any Markdown file can be opened in the editor. But when macOS tells the editor to open a file (e.g. from _Open With..._ in the context menu, or from Terminal with `open -a QLMarkdown README.md`) the editor starts, but it gives this error message:

<img width="372" alt="The document README.md could not be opened. QLMarkdown cannot open files in the Markdown Text format." src="https://user-images.githubusercontent.com/11797190/150565705-90379b6e-45fa-401d-be4a-33982ea495ca.png">

> The document "README.md" could not be opened. QLMarkdown cannot open files in the "Markdown Text" format.

I don't know what is meant by that – in the first place, the file opens just fine when opened with <kbd>⌘</kbd>+<kbd>O</kbd>, and in the second place, I don't think "Markdown text" is anything other than Markdown, right?

Anyway, I hope you find this of interest to worry about.

**Details**: QLMarkdown 1.0.10 (35), macOS 12.1 on a MacBook with Apple Silicon.

**Comment by sbarex** [comment]
I have implemented this behavior on the release 1.0.11 (36).
