### ISSUE TITLE
unable to install command line tool

### ISSUE THREAD

**Issue by lcn2** [sbarex/QLMarkdown#94]
Under macOS 12.2:

    QLMarkdown -> Install the command line tool

produces the error message:

    Unable to link the command line tool link into `/usr/local/bin/qlmarkdown_cli`!
    You don’t have permission to save the file “qlmarkdown_cli” in the folder “bin”.

even when /usr/local/bin is wide open mode 0777 (not a recommend permission -- just did that for testing purposes).

The 'Install the command line tool' functionality appears to not work under version 1.0.10.

**Comment by hazarek** [comment]
add this line to `~/.zprofile` file

`alias qlmarkdown_cli="/Applications/QLMarkdown.app/Contents/Resources/qlmarkdown_cli"`

**Comment by sbarex** [comment]
Must be fixed on the release 1.0.11 (36).
