### ISSUE TITLE
QLMarkdown v1.0.11 assumes /usr/local/bin is writable when installing the command line tool

### ISSUE THREAD

**Issue by lcn2** [sbarex/QLMarkdown#97]
Hello @hazarek,

Under macOS 12.2, and using QLMarkdown release 1.0.11 (36) and adding the line:

```
    qlmarkdown_cli=/Applications/QLMarkdown.app/Contents/Resources/qlmarkdown_cli
```

to **~/.zprofile** and rebooting and logging back in, the action:

```
    QLMarkdown -> Install the command line tool
```

will ONLY work if the directory **/usr/local/bin** is writable by the user.

Good security practice says that critical directories in the standard **$PATH** should **NOT** be writable to normal users.

I suggest that when QLMarkdown needs to writes into **/usr/local/bin**, then it should use a separate thread that attempts to elevate privilege before attempting to install something under /usr/local/bin (or at least if **/usr/local/bin** is not writable).  I.e., `Install the command line tool` should result in a macOS pop-up asking for the admin password before creating the **/usr/local/bin/qlmarkdown_cli** symlink.

Thanks again for a great tool.  Much appreciated!

chongo (Landon Curt Noll) /\oo/\

**Comment by sbarex** [comment]
Thanks for the comment.
Release 1.0.11 (36) successfully installs the CLI tool in `/usr/local/bin` so putting the alias in the `.zprofile` file is useless.

On security issues you are probably right, but I have adopted the homebrew example which installs executables in `/usr/local/bin` without requiring administrative privileges. 

Do you have any sample code to implement this functionality in a sandboxed app?

**Comment by lcn2** [comment]
For general stuff on how to safely elevate privilege, see following Apple developer document:

https://developer.apple.com/library/archive/documentation/Security/Conceptual/SecureCodingGuide/Articles/AccessControl.html

Perhaps there is an easier approach.  Detect if  /usr/local/bin is now writable:

```c
if (! access("/usr/local/bin", W_OK)) {
...
}
```

If it is NOT writable, issue a more useful error message asking the user to do the following in a shell / terminal window:

```sh
sudo /Applications/QLMarkdown.app/...something.../setup_the_symlink.sh
```

There are several advantages to doing this:

- The error message is useful: user's won't think you code as a _bug_ :-)
- You do not have to content with getting privilege elevation correct: do not need it
- A user can look at the **/Applications/QLMarkdown.app/...something.../setup_the_symlink.sh** script to see if they _want to run the code_
- Let sudo manage the privilege elevation

I hope this helps.

**Comment by sbarex** [comment]
Thanks so much for the suggestions and code examples!
On the commit 5109670ad9ab72324a57b199f1769d94018e12fd I have implemented these improvements.
